### ISSUE TITLE
Segmentation fualt - core dumped on vesion 3.10.0

### ISSUE THREAD

**Issue by arnosk** [reddcoin-project/reddcoin-3.10#157]
Just installed the newest version 3.10.0 (64 bit) on my mini pc running Ubuntu 18.04.4 LTS 
And I am getting a segmentation fault. The previous version v3.0.0.0-32682b beta 64bit worked correct.
Am I missing some libraries?

This is the backtrace:
```
(gdb) run
Starting program: /home/arno/workspace/coins/reddcoin2/reddcoin-3.10.0-64/bin/reddcoin-qt 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4f7a700 (LWP 4277)]

Thread 1 "reddcoin-qt" received signal SIGSEGV, Segmentation fault.
0x0000555555a71e9a in ?? ()
(gdb) backtrace
#0  0x0000555555a71e9a in ?? ()
#1  0x0000555555a5bf2f in ?? ()
#2  0x0000555555a5afdb in ?? ()
#3  0x000055555611b9b3 in ?? ()
#4  0x0000555555f0dff6 in ?? ()
#5  0x0000555555f0ee35 in ?? ()
#6  0x0000555556385e80 in ?? ()
#7  0x0000555556385ef5 in ?? ()
#8  0x0000555555f0f7a9 in ?? ()
#9  0x0000555555bd3ca2 in ?? ()
#10 0x00005555556a4712 in ?? ()
#11 0x00005555556b5888 in ?? ()
#12 0x00007ffff5c3cb97 in __libc_start_main (main=0x5555556b5830, argc=1, argv=0x7fffffffdf58, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf48)
    at ../csu/libc-start.c:310
#13 0x00005555556a31a9 in ?? ()
#14 0x00007fffffffdf48 in ?? ()
#15 0x000000000000001c in ?? ()
#16 0x0000000000000001 in ?? ()
#17 0x00007fffffffe2a2 in ?? ()
#18 0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by reddink** [comment]
The debug.log would also be helpful
My initial thoughts on this are that the issue is with the wallet.dat.
We have put a few additional checks in the wallet to verify integrity, and most issues we are seeing are where there is actually some level of corruption in the wallet.dat that wasn't detected with the earlier version, particularly with privkeys.

you seem to know your way around, so.
Suggestion would be to 
* create additional backups of wallet.dat file
* drop back to the earlier version of reddcoin core and start up,
* take a note of wallet balance.
* using either RPC or debug console,
   * perform a dumpwallet to export all readable privkeys and their metadata
* stop the reddcoin core
* rename the wallet.dat (another backup)
* your data directory should not have a wallet.dat file at this point as we want to start the new version and have a new wallet.dat file created
* start the new reddcoin core (3.10.0)
* use either RPC or debug console,
   * perform a importwallet to import the previous dumpfile.
* this should kick off a rescan at completion of the import
* after rescan completes - check the balance matches expected

let me know how you get on.

**Comment by arnosk** [comment]
I renamed the entire directory .reddcoin to test if the program would start up. But there was no new .reddcoin directory created. So no info in the debug.log. The program is hanging during the initialisation phase.

**Comment by reddink** [comment]
Ok, I have run up a vanilla VM of ubuntu 18.04 (64bit)
copied the new binary from the download site, extracted and was able to launch the qt wallet successfully without error or segfault.

The distributed binary of reddcoin is statically built, however there are a couple of shared libraries that it depends

my guess is it is qt version
3.0.0 on linux required QT4
3.10.0 on linux moved to QT5 for all platforms

could you run ldd -r ./reddcoin-qt and post the output
Thanks

**Comment by reddink** [comment]
Also, I have been making some assumptions,
What was your actual installation method?

**Comment by arnosk** [comment]
I just unpacked the tar.gz file to a directory and run ./reddcoin-qt
On my laptop (with Linux Mint 19.3 Tricia), I also had the same old version running, this worked out of the box.

The output off the ldd cmd is:
```
arno@grey1:~/workspace/coins/reddcoin2/reddcoin-3.10.0-64/bin$ ldd -r ./reddcoin-qt
	linux-vdso.so.1 (0x00007ffe33daf000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f6e1387b000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f6e13543000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f6e1331b000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f6e130d6000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f6e12e22000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6e12c03000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6e129ff000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6e127f7000)
	libanl.so.1 => /lib/x86_64-linux-gnu/libanl.so.1 (0x00007f6e125f3000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6e1226a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6e11ecc000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6e11cb4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6e118c3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6e15688000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f6e116bf000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f6e114b9000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f6e11287000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f6e11055000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6e10e38000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f6e10c23000)
```

**Comment by reddink** [comment]
What was your resolution for this?

**Comment by arnosk** [comment]
O sorry I accidently closed the issue (clicked the wrong button). 
It is not working yet
