### ISSUE TITLE
Unable to package .app into .dmg on OS X

### ISSUE THREAD

**Issue by raid5** [reddcoin-project/reddcoin-3.10#58]
From [release-process.md](https://github.com/reddcoin-project/reddcoin/blob/master/doc/release-process.md):

```
$ python2.7 contrib/macdeploy/macdeployqtplus Reddcoin-Qt.app -add-qt-tr $T -dmg -fancy contrib/macdeploy/fancy.plist
```

Result:

```
Traceback (most recent call last):
  File "contrib/macdeploy/macdeployqtplus", line 560, in <module>
    applicationBundle = ApplicationBundleInfo(target)
  File "contrib/macdeploy/macdeployqtplus", line 155, in __init__
    raise RuntimeError("Could not find bundle binary for " + path)
RuntimeError: Could not find bundle binary for dist/Reddcoin-Qt.app
```

**Comment by laudney** [comment]
cannot reproduce

**Comment by raid5** [comment]
Do you understand what the error is saying? I'm not too familiar with the process and the trace is a bit cryptic to me.
